/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AttachmentCleanerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  confirmBeforeDelete: true,
  showNotifications: true,
  includedExtensions: ["png", "jpg", "jpeg", "gif", "bmp", "svg", "webp", "pdf", "mp4", "webm", "mp3", "wav", "ogg", "flac"]
};
var AttachmentCleanerPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("trash-2", "Clean unattached files", () => {
      this.cleanUnattachedFiles();
    });
    this.addCommand({
      id: "clean-unattached-files",
      name: "Clean unattached files",
      callback: () => {
        this.cleanUnattachedFiles();
      }
    });
    this.addSettingTab(new AttachmentCleanerSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async cleanUnattachedFiles() {
    const unattachedFiles = await this.findUnattachedFiles();
    if (unattachedFiles.length === 0) {
      if (this.settings.showNotifications) {
        new import_obsidian.Notice("No unattached files found.");
      }
      return;
    }
    if (this.settings.confirmBeforeDelete) {
      new ConfirmationModal(this.app, unattachedFiles, (filesToDelete) => {
        this.deleteFiles(filesToDelete);
      }).open();
    } else {
      this.deleteFiles(unattachedFiles);
    }
  }
  async findUnattachedFiles() {
    const allFiles = this.app.vault.getFiles();
    const markdownFiles = this.app.vault.getMarkdownFiles();
    const potentialAttachments = allFiles.filter((file) => {
      const extension = file.extension.toLowerCase();
      return this.settings.includedExtensions.includes(extension);
    });
    const allMarkdownContent = [];
    for (const mdFile of markdownFiles) {
      const content = await this.app.vault.cachedRead(mdFile);
      allMarkdownContent.push(content);
    }
    const unattachedFiles = potentialAttachments.filter((file) => {
      return !this.isFileReferenced(file, allMarkdownContent);
    });
    return unattachedFiles;
  }
  isFileReferenced(file, allMarkdownContent) {
    const fileName = file.name;
    const baseName = file.basename;
    for (const content of allMarkdownContent) {
      if (content.includes(fileName) || content.includes(baseName)) {
        return true;
      }
    }
    return false;
  }
  async deleteFiles(files) {
    let deletedCount = 0;
    for (const file of files) {
      try {
        await this.app.vault.trash(file, false);
        deletedCount++;
      } catch (error) {
        console.error(`Failed to delete ${file.path}:`, error);
      }
    }
    if (this.settings.showNotifications) {
      new import_obsidian.Notice(`Moved ${deletedCount} unattached file(s) to trash.`);
    }
  }
};
var ConfirmationModal = class extends import_obsidian.Modal {
  constructor(app, files, onConfirm) {
    super(app);
    this.files = files;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Confirm File Deletion" });
    contentEl.createEl("p", {
      text: `Found ${this.files.length} unattached file(s). The following files will be moved to trash:`
    });
    const fileList = contentEl.createEl("div", { cls: "attachment-cleaner-file-list" });
    fileList.style.maxHeight = "300px";
    fileList.style.overflow = "auto";
    fileList.style.border = "1px solid var(--background-modifier-border)";
    fileList.style.borderRadius = "4px";
    fileList.style.padding = "8px";
    fileList.style.marginBottom = "16px";
    this.files.forEach((file) => {
      const fileItem = fileList.createEl("div", { text: file.path });
      fileItem.style.padding = "2px 0";
    });
    const buttonContainer = contentEl.createEl("div", { cls: "attachment-cleaner-buttons" });
    buttonContainer.style.display = "flex";
    buttonContainer.style.gap = "8px";
    buttonContainer.style.justifyContent = "flex-end";
    const cancelBtn = buttonContainer.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();
    const confirmBtn = buttonContainer.createEl("button", {
      text: `Move ${this.files.length} file(s) to trash`,
      cls: "mod-warning"
    });
    confirmBtn.onclick = () => {
      this.onConfirm(this.files);
      this.close();
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var AttachmentCleanerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Attachment Cleaner Settings" });
    new import_obsidian.Setting(containerEl).setName("Confirm before delete").setDesc("Show confirmation dialog before deleting files").addToggle((toggle) => toggle.setValue(this.plugin.settings.confirmBeforeDelete).onChange(async (value) => {
      this.plugin.settings.confirmBeforeDelete = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show notifications").setDesc("Show notifications when cleaning is complete").addToggle((toggle) => toggle.setValue(this.plugin.settings.showNotifications).onChange(async (value) => {
      this.plugin.settings.showNotifications = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("File extensions").setDesc("Comma-separated list of file extensions to consider as attachments").addTextArea((text) => text.setPlaceholder("png,jpg,jpeg,gif,pdf,mp4,mp3...").setValue(this.plugin.settings.includedExtensions.join(",")).onChange(async (value) => {
      this.plugin.settings.includedExtensions = value.split(",").map((ext) => ext.trim().toLowerCase()).filter((ext) => ext.length > 0);
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Usage" });
    containerEl.createEl("p", { text: "Click the trash icon in the ribbon or use the command palette to clean unattached files." });
    containerEl.createEl("p", { text: "Files are moved to the vault trash (.trash folder) and can be recovered if needed." });
  }
};
